services:
  - type: web
    name: house-price-prediction
    runtime: python
    envVars:
      - key: ENV
        value: production
    buildCommand: pip install -r requirements.txt
    startCommand: waitress-serve --port=8000 app:app
